version: '3'

services:
  eureka:
    image: maven:3.6.1-jdk-8
    ports:
      - '8761:8761'
    working_dir: /app
    volumes:
      - ./eureka-server:/app
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  api-gateway:
    image: maven:3.6.1-jdk-8
    ports:
      - '8080:8080'
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  postgresdev:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=dinoshanr
      - POSTGRES_DB=pgdev
  users-api:
    image: maven:3.6.1-jdk-8
    ports:
      - '8081:8081'
    working_dir: /app
    volumes:
      - ./users-api:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  events-api:
    image: maven:3.6.1-jdk-8
    ports:
      - '8082:8082'
    working_dir: /app
    volumes:
      - ./events-api:/app
    depends_on:
      - eureka
    command: 'mvn spring-boot:run'
    environment:
      - SPRING_PROFILES_ACTIVE=dev